name: 'Ensure Immutable Actions'
description: 'Validates third-party actions in your workflows are using immutable releases'

branding:
  icon: 'shield'
  color: 'blue'

inputs:
  github-token:
    description: 'GitHub token for API calls'
    required: true
    default: ${{ github.token }}
  fail-on-mutable:
    description: 'Fail the workflow if mutable actions are found'
    required: false
    default: 'true'
  workflows:
    description: 'Specific workflow files to check (comma-separated, e.g., ci.yml,deploy.yml). If not specified, checks ALL workflows in .github/workflows/'
    required: false
  exclude-workflows:
    description: 'Workflow files to exclude from checks (comma-separated). Only applies when workflows are not specified'
    required: false

outputs:
  mutable-actions:
    description: 'JSON array of actions using mutable releases'
  immutable-actions:
    description: 'JSON array of actions using immutable releases'
  first-party-actions:
    description: 'JSON array of first-party actions (actions/*, github/*, octokit/*)'
  all-passed:
    description: 'Boolean indicating if all checks passed'
  workflows-checked:
    description: 'List of workflow files that were checked'

runs:
  using: 'node20'
  main: 'dist/index.js'
